name: lab05
run-name: lab05
on: [push]
jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get data
        run: |
          cmake -H. -B_build -DBUILD_TESTS=ON -DBUILD_COVERAGE=ON
          cmake --build _build
          cmake --build _build --target test -- ARGS=--verbose
      - name: send_report_coveralls
        uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: third-party
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}